### ISSUE TITLE
Won/Lost/Drawn Wars

### ISSUE THREAD

**Issue by husseinm** [gunnertech/thumbwar-api#95]
Given a user - return a json response with the count and list of wars that have been won/lost/drawn.

Won/Lost/Drawn/Ongoing wars should probably be a separate API request each, but if you want it can be one big request.

**Comment by CodySwannGT** [comment]
This is actually in the API docs. The index api can take the following views: :view (required, enum: 'timeline' | 'mine' | 'public' | 'won' | 'lost')

"push" is not documented but it works.

**Comment by husseinm** [comment]
Currently 'mine' is in use for In-Progress. It appears mine does not return the ongoing wars, or at least the counts do not match... Does 'mine' give the in-Progress wars or something different since in-Progress is a new thing?

**Comment by CodySwannGT** [comment]
Mine is everything for the logged in user.


On Tuesday, June 16, 2015, Mahdi Hussein <notifications@github.com> wrote:

> Currently 'mine' is in use for In-Progress. It appears mine does not
> return the ongoing wars, or at least the counts do not match... Does 'mine'
> give the in-Progress wars or something different since in-Progress is a new
> thing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gunnertech/thumbwar-api/issues/95#issuecomment-112283783>
> .
>


-- 
 Cody Swann - CEO, Gunner Technology
T: 213.915.4083 | cody@gunnertech.com | www.gunnertech.com
<http://www.gunnertech.com/>Skype: cody.swann

*CONFIDENTIALITY NOTICE: This email message, together with any documents,
files and/or email messages attached to it, is intended for the sole use of
the individual or entity to whom it is addressed, and may contain
information that is legally privileged, confidential and restricted from
disclosure.  If you are not the intended recipient, or responsible for
delivery to that person, you are hereby notified that any dissemination or
copying of this communication is STRICTLY PROHIBITED.  In such case please
notify the sender by reply email and delete this message without reading,
printing or saving.*

**Comment by husseinm** [comment]
Hmm, I am pretty sure Jiake wanted In-Progress to be that users in-progress wars and not everything. Is it possible to get a view that does that?

**Comment by husseinm** [comment]
Ok so I believe the 'push' view may have a caching issue. Won/Lost are perfect. The tied and in-progress counts are also perfect. 

An issue I am getting is the wrong wars are being sent back when using the push view; For your profile I receive a complete mismatch in count of wars, and for others I just don't get any wars even when their count indicates they do indeed have tied wars. Here are the API requests I am using:

https://thumbwar-api-staging.herokuapp.com/users/1/thumbwars?token=STUFF&facebook_id=STUFF&view=won
https://thumbwar-api-staging.herokuapp.com/users/1/thumbwars?token=STUFF&facebook_id=STUFF&view=lost
https://thumbwar-api-staging.herokuapp.com/users/1/thumbwars?token=STUFF&facebook_id=STUFF&view=push
https://thumbwar-api-staging.herokuapp.com/users/1/thumbwars?token=STUFF&facebook_id=STUFF&view=mine

**Comment by CodySwannGT** [comment]
ok. I think we're good on both counts now.

**Comment by husseinm** [comment]
The 'push' view now operates correctly, thank you!

Will we be making the 'mine' view return users in-progress counts? Will we simply create a new 'in-progress' view? Or will we not be adding that feature?

**Comment by CodySwannGT** [comment]
oh sorry. you can now pass "in_progress" as a view parameter

On Tue, Jun 16, 2015 at 1:34 PM, Mahdi Hussein <notifications@github.com>
wrote:

> The 'push' view now operates correctly, thank you!
>
> Will we be making the 'mine' view return users in-progress counts? Will we
> simply create a new 'in-progress' view? Or will we not be adding that
> feature?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gunnertech/thumbwar-api/issues/95#issuecomment-112508331>
> .
>



-- 
 Cody Swann - CEO, Gunner Technology
T: 213.915.4083 | cody@gunnertech.com | www.gunnertech.com
<http://www.gunnertech.com/>Skype: cody.swann

*CONFIDENTIALITY NOTICE: This email message, together with any documents,
files and/or email messages attached to it, is intended for the sole use of
the individual or entity to whom it is addressed, and may contain
information that is legally privileged, confidential and restricted from
disclosure.  If you are not the intended recipient, or responsible for
delivery to that person, you are hereby notified that any dissemination or
copying of this communication is STRICTLY PROHIBITED.  In such case please
notify the sender by reply email and delete this message without reading,
printing or saving.*

**Comment by husseinm** [comment]
The in_progress view is returning more wars than the in_progress count I get for that user, this is the request being made:

https://thumbwar-api-staging.herokuapp.com/users/60/thumbwars?token=STUFF&facebook_id=STUFF&view=in_progress

**Comment by CodySwannGT** [comment]
try now

**Comment by husseinm** [comment]
After that restart there it worked! Now closing the issue, thank you!
